---
title: "Schedule"
format: html
order: 1
---

Course weeks with modules follow a consistent cycle:

| Tuesday                                                  | Thursday                                   |
|:--------------------------------------------------------:|:------------------------------------------:|
| In class review & peer instruction of Learning Module(s) | Hands-on Lab work in class                 |
| In class quiz (for bonus) of Learning Module(s)          | Lab(s) due following Wednesday at 11:59 PM |

::: {.callout-tip}
All Learning Modules will be available by the start of the week. It is expected that you review the week's Learning Module(s) before class on the respective Tuesday.
:::

## Calendar

- Individual Learning Modules are in **bold**.
- **Labs**: due on Wednesday at 11:59 PM of the following week.
  - **Example - Week 7**:
    - Tuesday (2025-02-25), we will go over the exercises from **Intro to Data Science**.
    - Thursday (2025-02-27), you will work on **Lab 5** in class.
    - Wednesday (2025-03-05), **Lab 5** is due.
- **Tests**: due on Wednesday at 11:59 PM following the review week.
  - **Example - Test 1**:
    - Tuesday (2025-02-18): No new lecture material for this week, give time to ask questions for test.
    - Wednesday (2025-02-19): Test is due at 11:59 PM.
    - Thursday (2025-02-20): We will go through the test problems in class.
- **Final Project**: due at 11:59 PM on Monday, April 28th, 2025.

*Schedule subject to change, changes will be announced in class and on eCampus.*

::: {.column-body-outset}
| Week | Start      | Learning Module(s)                                   | Course Deliverable(s) Due |
|:----:|:----------:|------------------------------------------------------|---------------------------|
| 1    | 2025-01-13 | Course Intro                                         |                           |
| 2    | 2025-01-20 | **Setting Up Your Workstation**                      |                           |
| 3    | 2025-01-27 | **Intro to Python**                                  | Lab 1                     |
| 4    | 2025-02-03 | **Flow Control and Functions**                       | Lab 2                     |
| 5    | 2025-02-10 | **Data Structures**                                  | Lab 3                     |
| 6    | 2025-02-17 | Test 1 Prep                                          | Lab 4                     |
| 7    | 2025-02-24 | **Intro to Data Science**                            | **Test 1**                |
| 8    | 2025-03-03 | **Data Visualization**                               | Lab 5                     |
| 9    | 2025-03-10 | **Data Transformation**                              | Lab 6                     |
| 10   | 2025-03-17 | **Data Communication**                               | Lab 7                     |
| 11   | 2025-03-24 | *Spring Recess*                                      | *Recess*                  |
| 12   | 2025-03-31 | Test 2 Prep                                          | Lab 8                     |
| 13   | 2025-04-07 | **SQL for Data Analysis**                            | **Test 2**                |
| 14   | 2025-04-14 | **Excel for Data Analysis**                          | Lab 9                     |
| 15   | 2025-04-21 | Final Project Prep                                   | Lab 10                    |
| 16   | 2025-04-28 | Presentations                                        | **Final Project**         |
| 17   | 2025-05-05 | Finals Week (No Final)                               |                           |
:::
