---
title: "03 | Functions and Flow Control"
subtitle: "Learn about the basics of Python."
format: html
order: 3
---

## Functions

So far we've used several built in Python functions. Now we will learn how to write our own. We'll also see how one function can call another.

### Defining new functions

A **function definition** specifies the name of a new function and the sequence of statements that run whe the function is called:

```{python}
def print_lyrics():
    print("Almost heaven, West Virginia")
    print("Blue ridge mountains, Shenandoah river")
```

`def` is a keyword that indicates that this is a function definition. The name of this function is `print_lyrics`. Anything that's a legal variable name is also a legal function name.

The empty parenthesis indicates that this function doesn't take any arguments.

The first line of the function definition is called the **header**, the rest is caleld the **body**. The header has to end with a colon and the body has to be indented, usually four spaces.

Defining a function creates a **function object**:

```{python}
print_lyrics
```

The output shows that `print_lyrics` is a function that takes no arguments. `__main__` is the name of the module that contains `print_lyrics`. !!! EXPLAIN `__main__` BETTER HERE !!!